[reflection.assembly]::LoadWithPartialName( "System.Drawing" ) > $null;
$Bitmap = New-Object System.Drawing.Bitmap {{width}}, {{height}};
$Size = New-Object System.Drawing.Size {{width}}, {{height}};
$FromImage = [System.Drawing.Graphics]::FromImage( $Bitmap );
$FromImage.CopyFromScreen( {{x}}, {{y}}, 0, 0, $size );
$MemoryStream = New-Object System.IO.MemoryStream;
$Bitmap.save( $MemoryStream, [System.Drawing.Imaging.ImageFormat]::png );
$Bytes = $MemoryStream.ToArray();
$MemoryStream.Flush();
$MemoryStream.Dispose();
$FromImage.Dispose();
$Bitmap.Dispose();
return [convert]::ToBase64String( $Bytes );